### ISSUE TITLE
Great job, thanks!

### ISSUE THREAD

**Issue by atbohmer** [StamusNetworks/KTS6#1]
Hello,
Just upgraded from ELK 5.6 to ELK 6.4, running already Suricata 4.1rc1 and loaded the KTS6 dashboards and all seems well and dashboards are really looking good. Great job and much appreciated!
Do you advise to perform a reindex on the migrated E data?
Cheers,
Andre

**Comment by pevma** [comment]
Thank you for the feed back!
Yes reindexing should be good - you could try the script here (just run it locally - should be good as well) - https://github.com/StamusNetworks/SELKS/blob/SELKS5/scripts/SELKS4-SELKS5/SN-S4-S5-ES-Reindex.sh
