### ISSUE TITLE
Dashboards and Visulisation KTS6 not supported on Kibana 7

### ISSUE THREAD

**Issue by phoenixml** [StamusNetworks/KTS6#10]
Hi Selks Team,

Dashboards and Visulisation KTS6 not supported on Kibana 7"
"Sorry, there was an error
Saved objects file format is invalid and cannot be imported"

any advice how to solve this issue?

Thank you.

**Comment by pevma** [comment]
Hi there,
Thank you for trying out the dashboards. They are currently only ELK 6 compatible, not yet ELK 7.
Any feedback or fixes are welcome though for sure - as we will start looking into ELK 7 upgrades.Thanks!

**Comment by phoenixml** [comment]
Hi thank you for your reply , I will be checking how to upgrade them, and if I succeeded I will share with the community thanks 👍🏻

**Comment by pevma** [comment]
any help is much appreciated
