### ISSUE TITLE
No alrets on map

### ISSUE THREAD

**Issue by rootbdfy** [StamusNetworks/KTS6#2]
Hello!
First of all I want to say thank you for dashboards.
But I have problem with map : no any point on map and error :
![default](https://user-images.githubusercontent.com/18612349/48128508-bb976380-e297-11e8-89c3-cc3f364a6d08.png)
I've tried reindex, but it did not help.

**Comment by pevma** [comment]
You need to go to Kibana indexes (management) and refresh/update (button) all the mappings .

**Comment by rootbdfy** [comment]
Thx for the answer.
Refresh/update did not help.
![default](https://user-images.githubusercontent.com/18612349/48129727-64938d80-e29b-11e8-937f-6a2142d6fd91.png)

**Comment by pevma** [comment]
I think those are two separate issues.
One is refresh the indexes which you already did. (btw you need to do it for all of the indexes  ``logstash-......``)

Two - no alerts on the map - 
The alerts on th e maps will appear only if there is a public IP in the alert. If the IPs generating the alerts are form the private ranges- they will not appear simple because there is no geoip location.

**Comment by pevma** [comment]
Aslo - looking at your screenshot - you are not at the correct place. You need to go to Kibana's indexes.

**Comment by rootbdfy** [comment]
Sorry, I messed up ES indices and Kibana indices.
I've refreshd indexes, and got error on map : "Could not locate that index-pattern-field (id: geoip.location)".
I use logstash template from your [git](https://github.com/StamusNetworks/selks-scripts/blob/master/Scripts/Configs/SELKS4/Logstash/etc/logstash/conf.d/logstash.conf) and see that **geoip.location** not sended.

**Comment by pevma** [comment]
Where do you see that err?

**Comment by rootbdfy** [comment]
![default](https://user-images.githubusercontent.com/18612349/48134493-230ade80-e2ab-11e8-809a-7973521b7103.png)

**Comment by pevma** [comment]
Is this a case where you only have internal/private range IPs ?

**Comment by rootbdfy** [comment]
No. I have a lot of data with geoip.coordinates , but no data with geoip.location.
![default](https://user-images.githubusercontent.com/18612349/48250723-4bf8b400-e410-11e8-94f6-c329579acda4.png)

**Comment by pevma** [comment]
I think you may also need the `logstash.conf` form here  - the geoip part. 
https://github.com/StamusNetworks/SELKS/blob/SELKS5/staging/etc/logstash/conf.d/logstash.conf

**Comment by rootbdfy** [comment]
Doh, thx for link.
All work fine !
