### ISSUE TITLE
dashboard:SN-TLS.json timeFrom

### ISSUE THREAD

**Issue by atbohmer** [StamusNetworks/KTS6#3]
Hello,

All dashboards have a timeFrom setting of 24h but dashboard:SN-TLS.json has a "timeFrom":"now-6M", six months. Could you please also make this 24h?
I always modify this setting before importing the dashboards (saves some load on the ELK node), but missed this one.

$ sed -i 's/now-24h/now-1h/g' dashboards/dashboard/* && ./load.sh

Cheers,
Andre

**Comment by pevma** [comment]
You could modify it yourself and then use it like that - that should work right ? The time frame is up for adjustment any way you need - so no issue.

**Comment by atbohmer** [comment]
Indeed no issue, but inconsistent, but no problem to modify is by myself.

**Comment by pevma** [comment]
Apologizes  -  i totally misread your comment.
Yes sure make sense to homogenize the whole output.

I have adjusted it to the default 24hr here - https://github.com/StamusNetworks/KTS6/commit/a8c8ff890739c8e7de95dda0b3a8a7e64c302c3f 
Could you please confirm it is working as expected and close the bug report if so.
Thank you

**Comment by atbohmer** [comment]
No problem, just confirmed your fix, thanks!
