### ISSUE TITLE
Unable to display Dashboards

### ISSUE THREAD

**Issue by lukelee1987** [StamusNetworks/KTS6#7]
![image](https://user-images.githubusercontent.com/29053050/50270969-3a261a00-046e-11e9-855b-e6d6b822bcc4.png)

Dear all, I am using this KTS6, but unable to display the dashboards. Together with Synesis plugin. Anyone encountered this issue before? https://github.com/robcowart/synesis_lite_suricata#environment-variable-reference

**Comment by pevma** [comment]
I am not sure this is KTS6 problem.
You should seek support from  the vendor you are using.
